spring:
  application:
    name: mym-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/manage-your-money-org/mym-configurations
          username: ${github.username}
          password: ${github.password.token}
          default-label: ${config.branch:main}


server:
  port: 8727
  
encrypt:
  key: ${encryption.secret.key}

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
      base-path: "/mym/${spring.application.name}/actuator"