spring:
  application:
    name: mym-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/manage-your-money-org/mym-configurations
          username: rkumar0206
          password: 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
          default-label: ${config.branch:main}


server:
  port: 8727
  
encrypt:
  key: asbahjbcjhabjhabjcbj%%$#Q$7hdbsjhbjbbEA$A$AT8897____q5656541646

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
      base-path: "/mym/${spring.application.name}/actuator"